// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa zapytania o pojedynczy rachunek / Account Information Request
    /// Class
    /// </summary>
    public partial class AccountInfoRequest
    {
        /// <summary>
        /// Initializes a new instance of the AccountInfoRequest class.
        /// </summary>
        public AccountInfoRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountInfoRequest class.
        /// </summary>
        /// <param name="accountNumber">Numer rachunku / Account number</param>
        public AccountInfoRequest(RequestHeaderAIS requestHeader, string accountNumber)
        {
            RequestHeader = requestHeader;
            AccountNumber = accountNumber;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestHeader")]
        public RequestHeaderAIS RequestHeader { get; set; }

        /// <summary>
        /// Gets or sets numer rachunku / Account number
        /// </summary>
        [JsonProperty(PropertyName = "accountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RequestHeader == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RequestHeader");
            }
            if (AccountNumber == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AccountNumber");
            }
            if (RequestHeader != null)
            {
                RequestHeader.Validate();
            }
        }
    }
}
