// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa odpowiedzi na zapytania o konto PSU / PSU's Account Response
    /// Class
    /// </summary>
    public partial class AccountResponse
    {
        /// <summary>
        /// Initializes a new instance of the AccountResponse class.
        /// </summary>
        public AccountResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountResponse class.
        /// </summary>
        public AccountResponse(ResponseHeader responseHeader, AccountInfo account = default(AccountInfo))
        {
            ResponseHeader = responseHeader;
            Account = account;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseHeader")]
        public ResponseHeader ResponseHeader { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public AccountInfo Account { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ResponseHeader == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ResponseHeader");
            }
            if (Account != null)
            {
                Account.Validate();
            }
        }
    }
}
