// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Klasa zawierająca dane banku / Bank Data Class
    /// </summary>
    public partial class BankAccountInfo
    {
        /// <summary>
        /// Initializes a new instance of the BankAccountInfo class.
        /// </summary>
        public BankAccountInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BankAccountInfo class.
        /// </summary>
        /// <param name="bicOrSwift">Numer BIC/SWIFT Banku / BIC/SWIFT
        /// number</param>
        /// <param name="name">Nazwa Banku / Bank's name</param>
        public BankAccountInfo(string bicOrSwift = default(string), string name = default(string), IList<string> address = default(IList<string>))
        {
            BicOrSwift = bicOrSwift;
            Name = name;
            Address = address;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets numer BIC/SWIFT Banku / BIC/SWIFT number
        /// </summary>
        [JsonProperty(PropertyName = "bicOrSwift")]
        public string BicOrSwift { get; set; }

        /// <summary>
        /// Gets or sets nazwa Banku / Bank's name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public IList<string> Address { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (BicOrSwift != null)
            {
                if (BicOrSwift.Length > 11)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "BicOrSwift", 11);
                }
            }
            if (Name != null)
            {
                if (Name.Length > 70)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Name", 70);
                }
            }
        }
    }
}
