// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models.AIS.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa zawierająca dane pozwalajace na korzystanie z mechanizmu
    /// stronicowania / Paging Information Class
    /// </summary>
    public partial class PageInfo
    {
        /// <summary>
        /// Initializes a new instance of the PageInfo class.
        /// </summary>
        public PageInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PageInfo class.
        /// </summary>
        /// <param name="previousPage">Użyte w celu stronicowania danych:
        /// poprzednia strona (np: numer konta lub transakcji rozpoczynający
        /// poprzednią stronę) / Previous page</param>
        /// <param name="nextPage">Użyte w celu stronicowania danych: następna
        /// strona (np: numer konta lub transakcji rozpoczynający następną
        /// stronę) / Next page</param>
        public PageInfo(string previousPage = default(string), string nextPage = default(string))
        {
            PreviousPage = previousPage;
            NextPage = nextPage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets użyte w celu stronicowania danych: poprzednia strona
        /// (np: numer konta lub transakcji rozpoczynający poprzednią stronę) /
        /// Previous page
        /// </summary>
        [JsonProperty(PropertyName = "previousPage")]
        public string PreviousPage { get; set; }

        /// <summary>
        /// Gets or sets użyte w celu stronicowania danych: następna strona
        /// (np: numer konta lub transakcji rozpoczynający następną stronę) /
        /// Next page
        /// </summary>
        [JsonProperty(PropertyName = "nextPage")]
        public string NextPage { get; set; }

    }
}
