// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa reprezentująca informacje o karcie w ramach transakcji /
    /// Transaction Card Information Class
    /// </summary>
    public partial class TransactionInfoCard
    {
        /// <summary>
        /// Initializes a new instance of the TransactionInfoCard class.
        /// </summary>
        public TransactionInfoCard()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionInfoCard class.
        /// </summary>
        /// <param name="cardHolder">Właściciel karty / Card holder</param>
        /// <param name="cardNumber">Numer karty / Card number</param>
        public TransactionInfoCard(string cardHolder = default(string), string cardNumber = default(string))
        {
            CardHolder = cardHolder;
            CardNumber = cardNumber;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets właściciel karty / Card holder
        /// </summary>
        [JsonProperty(PropertyName = "cardHolder")]
        public string CardHolder { get; set; }

        /// <summary>
        /// Gets or sets numer karty / Card number
        /// </summary>
        [JsonProperty(PropertyName = "cardNumber")]
        public string CardNumber { get; set; }

    }
}
