// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models.PIS
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa informacji o płatności / Payment Information Class
    /// </summary>
    public partial class PaymentInfo
    {
        /// <summary>
        /// Initializes a new instance of the PaymentInfo class.
        /// </summary>
        public PaymentInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentInfo class.
        /// </summary>
        /// <param name="transactionId">Identyfiaktor płatności / Transaction
        /// ID</param>
        /// <param name="generalStatus">Possible values include: 'submitted',
        /// 'cancelled', 'pending', 'done', 'rejected'</param>
        /// <param name="detailedStatus">Szczegółowy status płatności /
        /// Detailed payment status</param>
        public PaymentInfo(string transactionId, string generalStatus, string detailedStatus)
        {
            TransactionId = transactionId;
            GeneralStatus = generalStatus;
            DetailedStatus = detailedStatus;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets identyfiaktor płatności / Transaction ID
        /// </summary>
        [JsonProperty(PropertyName = "transactionId")]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'submitted', 'cancelled',
        /// 'pending', 'done', 'rejected'
        /// </summary>
        [JsonProperty(PropertyName = "generalStatus")]
        public string GeneralStatus { get; set; }

        /// <summary>
        /// Gets or sets szczegółowy status płatności / Detailed payment status
        /// </summary>
        [JsonProperty(PropertyName = "detailedStatus")]
        public string DetailedStatus { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (TransactionId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TransactionId");
            }
            if (GeneralStatus == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "GeneralStatus");
            }
            if (DetailedStatus == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DetailedStatus");
            }
        }
    }
}
