// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models.PIS
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa zapytania o status płatności / Payment Request Class
    /// </summary>
    public partial class PaymentRequest
    {
        /// <summary>
        /// Initializes a new instance of the PaymentRequest class.
        /// </summary>
        public PaymentRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentRequest class.
        /// </summary>
        /// <param name="transactionId">Identyfikator płatności / Transaction
        /// ID</param>
        public PaymentRequest(RequestHeader requestHeader, string transactionId)
        {
            RequestHeader = requestHeader;
            TransactionId = transactionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestHeader")]
        public RequestHeader RequestHeader { get; set; }

        /// <summary>
        /// Gets or sets identyfikator płatności / Transaction ID
        /// </summary>
        [JsonProperty(PropertyName = "transactionId")]
        public string TransactionId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RequestHeader == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RequestHeader");
            }
            if (TransactionId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TransactionId");
            }
            if (RequestHeader != null)
            {
                RequestHeader.Validate();
            }
            if (TransactionId != null)
            {
                if (TransactionId.Length > 14)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "TransactionId", 14);
                }
            }
        }
    }
}
