// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models.PIS
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Klasa odpowiedzi na pytanie o wiele płatności
    /// </summary>
    public partial class PaymentsResponse
    {
        /// <summary>
        /// Initializes a new instance of the PaymentsResponse class.
        /// </summary>
        public PaymentsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentsResponse class.
        /// </summary>
        public PaymentsResponse(ResponseHeader responseHeader, IList<PaymentInfo> payments = default(IList<PaymentInfo>))
        {
            ResponseHeader = responseHeader;
            Payments = payments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseHeader")]
        public ResponseHeader ResponseHeader { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payments")]
        public IList<PaymentInfo> Payments { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ResponseHeader == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ResponseHeader");
            }
            if (Payments != null)
            {
                foreach (var element in Payments)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
