// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models.PIS
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Klasa zapytania o statusy wielu płatności / Payments Request Class
    /// </summary>
    public partial class PaymentsRequest
    {
        /// <summary>
        /// Initializes a new instance of the PaymentsRequest class.
        /// </summary>
        public PaymentsRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentsRequest class.
        /// </summary>
        public PaymentsRequest(RequestHeaderWithoutToken requestHeader, IList<string> paymentsId)
        {
            RequestHeader = requestHeader;
            PaymentsId = paymentsId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestHeader")]
        public RequestHeaderWithoutToken RequestHeader { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paymentsId")]
        public IList<string> PaymentsId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RequestHeader == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RequestHeader");
            }
            if (PaymentsId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PaymentsId");
            }
        }
    }
}
