// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models.PIS
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Klasa zawierająca dane odbiorcy używana w żądaniach PIS / PIS Recipient
    /// Data Class
    /// </summary>
    public partial class RecipientPIS
    {
        /// <summary>
        /// Initializes a new instance of the RecipientPIS class.
        /// </summary>
        public RecipientPIS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RecipientPIS class.
        /// </summary>
        /// <param name="name">Recipient's name / Name</param>
        public RecipientPIS(string accountNumber, string name, IList<string> address = default(IList<string>))
        {
            AccountNumber = accountNumber;
            Name = name;
            Address = address;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Gets or sets recipient's name / Name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public IList<string> Address { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AccountNumber == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AccountNumber");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Name != null)
            {
                if (Name.Length > 140)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Name", 140);
                }
            }
        }
    }
}
