// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models.PIS
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Klasa zawierająca dane odbiorcy używana w żądaniach PIS dla operacji
    /// podatkowych / PIS Tax Recipient Data Class
    /// </summary>
    public partial class RecipientPISTax
    {
        /// <summary>
        /// Initializes a new instance of the RecipientPISTax class.
        /// </summary>
        public RecipientPISTax()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RecipientPISTax class.
        /// </summary>
        public RecipientPISTax(string accountNumber, IList<string> address)
        {
            AccountNumber = accountNumber;
            Address = address;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public IList<string> Address { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AccountNumber == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AccountNumber");
            }
            if (Address == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Address");
            }
        }
    }
}
