// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models.PIS
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa zawierająca dane nadawcy używana w żądaniach PIS / PIS Sender
    /// Data Class
    /// </summary>
    public partial class SenderPIS
    {
        /// <summary>
        /// Initializes a new instance of the SenderPIS class.
        /// </summary>
        public SenderPIS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SenderPIS class.
        /// </summary>
        /// <param name="name">Nazwa nadawcy / Sender name</param>
        public SenderPIS(string accountNumber, string name = default(string))
        {
            AccountNumber = accountNumber;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Gets or sets nazwa nadawcy / Sender name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AccountNumber == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AccountNumber");
            }
            if (Name != null)
            {
                if (Name.Length > 140)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Name", 140);
                }
            }
        }
    }
}
