// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Klasa odpowiedzi na zapytania o wiele kont PSU / PSU's Multiple
    /// Accounts Response Class
    /// </summary>
    public partial class AccountsResponse
    {
        /// <summary>
        /// Initializes a new instance of the AccountsResponse class.
        /// </summary>
        public AccountsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountsResponse class.
        /// </summary>
        public AccountsResponse(ResponseHeader responseHeader, IList<AccountBaseInfo> accounts = default(IList<AccountBaseInfo>), PageInfo pageInfo = default(PageInfo))
        {
            ResponseHeader = responseHeader;
            Accounts = accounts;
            PageInfo = pageInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseHeader")]
        public ResponseHeader ResponseHeader { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "accounts")]
        public IList<AccountBaseInfo> Accounts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pageInfo")]
        public PageInfo PageInfo { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ResponseHeader == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ResponseHeader");
            }
            if (Accounts != null)
            {
                foreach (var element in Accounts)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
