// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for deleteConsent operation.
    /// </summary>
    public partial class DeleteConsentHeaders
    {
        /// <summary>
        /// Initializes a new instance of the DeleteConsentHeaders class.
        /// </summary>
        public DeleteConsentHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeleteConsentHeaders class.
        /// </summary>
        /// <param name="contentEncoding">Gzip, deflate</param>
        public DeleteConsentHeaders(string contentEncoding = default(string))
        {
            ContentEncoding = contentEncoding;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets gzip, deflate
        /// </summary>
        [JsonProperty(PropertyName = "Content-Encoding")]
        public string ContentEncoding { get; set; }

    }
}
