// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa zawierająca dane elementu/pozycji słownika / Dictionary Item
    /// Class
    /// </summary>
    public partial class DictionaryItem
    {
        /// <summary>
        /// Initializes a new instance of the DictionaryItem class.
        /// </summary>
        public DictionaryItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DictionaryItem class.
        /// </summary>
        /// <param name="code">Kod pozycji słownika / Code</param>
        /// <param name="description">Opis pozycji słownika /
        /// Description</param>
        public DictionaryItem(string code = default(string), string description = default(string))
        {
            Code = code;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets kod pozycji słownika / Code
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets opis pozycji słownika / Description
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
