// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa zawierająca zwrotne metadane / Metadata Class
    /// </summary>
    public partial class ResponseHeader
    {
        /// <summary>
        /// Initializes a new instance of the ResponseHeader class.
        /// </summary>
        public ResponseHeader()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResponseHeader class.
        /// </summary>
        /// <param name="requestId">Identyfikator żądania / Request ID</param>
        /// <param name="sendDate">Data odpowiedzi, format:
        /// 2017-11-24T14:13:05.424Z / Send date</param>
        public ResponseHeader(string requestId = default(string), string sendDate = default(string))
        {
            RequestId = requestId;
            SendDate = sendDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets identyfikator żądania / Request ID
        /// </summary>
        [JsonProperty(PropertyName = "requestId")]
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or sets data odpowiedzi, format: 2017-11-24T14:13:05.424Z /
        /// Send date
        /// </summary>
        [JsonProperty(PropertyName = "sendDate")]
        public string SendDate { get; set; }

    }
}
