// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Api.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Klasa informacji danych dla przelewu do ZUS / ZUS Transfer Information
    /// Class
    /// </summary>
    public partial class TransactionInfoZUS
    {
        /// <summary>
        /// Initializes a new instance of the TransactionInfoZUS class.
        /// </summary>
        public TransactionInfoZUS()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TransactionInfoZUS class.
        /// </summary>
        /// <param name="contributionType">Typ wpłaty / Payment type</param>
        /// <param name="periodId">Numer okresu / Period number</param>
        /// <param name="year">Rok okresu / Period year</param>
        /// <param name="paymentTypeId">Identyfikator typu płatności / Payment
        /// type ID</param>
        public TransactionInfoZUS(Payor payerInfo = default(Payor), string contributionType = default(string), string periodId = default(string), double? year = default(double?), string paymentTypeId = default(string))
        {
            PayerInfo = payerInfo;
            ContributionType = contributionType;
            PeriodId = periodId;
            Year = year;
            PaymentTypeId = paymentTypeId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payerInfo")]
        public Payor PayerInfo { get; set; }

        /// <summary>
        /// Gets or sets typ wpłaty / Payment type
        /// </summary>
        [JsonProperty(PropertyName = "contributionType")]
        public string ContributionType { get; set; }

        /// <summary>
        /// Gets or sets numer okresu / Period number
        /// </summary>
        [JsonProperty(PropertyName = "periodId")]
        public string PeriodId { get; set; }

        /// <summary>
        /// Gets or sets rok okresu / Period year
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public double? Year { get; set; }

        /// <summary>
        /// Gets or sets identyfikator typu płatności / Payment type ID
        /// </summary>
        [JsonProperty(PropertyName = "paymentTypeId")]
        public string PaymentTypeId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (PayerInfo != null)
            {
                PayerInfo.Validate();
            }
            if (ContributionType != null)
            {
                if (ContributionType.Length > 1)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "ContributionType", 1);
                }
            }
            if (PeriodId != null)
            {
                if (PeriodId.Length > 2)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "PeriodId", 2);
                }
            }
            if (PaymentTypeId != null)
            {
                if (PaymentTypeId.Length > 1)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "PaymentTypeId", 1);
                }
            }
        }
    }
}
